/**
 * Builds the WebView plugin harness into a self-contained IIFE string and
 * writes it to `harness-bundle.ts` as `export const HARNESS_JS = "..."`.
 *
 * The harness runs inside a hidden react-native-webview (full WebKit), so we
 * target the browser platform and inline EVERYTHING — including the singlefile
 * QuickJS WASM (base64-embedded by @jitl/quickjs-singlefile-browser-release-sync).
 * The output is committed so CI/dev never need esbuild at runtime; regenerate
 * with `pnpm --filter @musex/mobile run build:plugin-harness` whenever the
 * harness or @musex/plugin-host/sandbox changes.
 *
 * Run: node src/plugins/harness/build-harness.mjs
 */

import { build } from "esbuild";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { writeFileSync } from "node:fs";

const here = dirname(fileURLToPath(import.meta.url));
const entry = join(here, "harness.ts");
const outFile = join(here, "harness-bundle.ts");

const result = await build({
  entryPoints: [entry],
  bundle: true,
  format: "iife",
  platform: "browser",
  target: "es2020",
  minify: true,
  write: false,
  // The unused desktop loader (`@musex/plugin-host/sandbox` barrel re-exports
  // `loadSandboxedPlugin`, which imports node:fs/promises + node:path) is dead
  // code in the harness — mobile never calls it. With `sideEffects:false` on
  // the package, esbuild tree-shakes the loader away; marking the node builtins
  // external stops esbuild erroring on their resolution during the graph walk
  // (the references are dropped before they reach the bundle, so no runtime
  // require() is emitted — verified absent in the output below).
  external: ["node:*"],
  logLevel: "info",
});

const out = result.outputFiles[0];
if (!out) {
  throw new Error("esbuild produced no output");
}
const code = out.text;

const header =
  "// AUTO-GENERATED by build-harness.mjs — DO NOT EDIT.\n" +
  "// Regenerate with: pnpm --filter @musex/mobile run build:plugin-harness\n" +
  "// biome-ignore-all lint: generated bundle (minified IIFE with inlined WASM)\n";

writeFileSync(outFile, `${header}export const HARNESS_JS = ${JSON.stringify(code)};\n`, "utf-8");

console.log(`Wrote ${outFile} (${(code.length / 1024).toFixed(1)} KB of harness JS)`);
