/// <reference types="vite/client" />
import type { MusexApi } from "../../shared/ipc-contract";

declare global {
  interface Window {
    musex: MusexApi;
  }

  /** Injected by vite `define` from package.json (electron.vite.config.ts). */
  const __APP_VERSION__: string;
}

/** Generated by scripts/generate-licenses.mjs (`pnpm gen:licenses`). Declared
 *  here (instead of resolveJsonModule) so tsc never type-infers the ~84KB file. */
declare module "*/generated/licenses.json" {
  const entries: Array<{
    name: string;
    version: string;
    license: string;
    homepage: string | null;
    description: string | null;
    licenseText: string | null;
  }>;
  export default entries;
}
